name: Deploy

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_VERSION: latest # ${{ github.ref_name }}_${{ github.sha }}
  GKE_CLUSTER: dinhnq-cluster-1
  GKE_ZONE: asia-southeast1-c

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

  deploy:
    name: Deploy Container
    needs:
      - ci
    if: |
      always() &&
      (needs.ci.result == 'success' || needs.ci.result == 'cancelled')     
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup gcloud CLI
      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Deploy to server
        run: |
          kubectl apply -f ./manifest.yml

      - name: Check deployment
        run: |
          # Wait for container to start
          sleep 20
          kubectl get ingress -n online-shop 